### ISSUE TITLE
PGMP not detected as a music application

### ISSUE THREAD

**Issue by tj28** [smithdtyler/prettygoodmusicplayer#92]
On my Xiaomi Redmi 2, PGMP is not detected as a music application. Launcher version did not help. This phone runs MIUI 6 on KitKat. (Also, the launcher version thinks PGMP is a system launcher)

Select default music app screen; PGMP missing:
![screenshot_2015-07-29-06-58-18](https://cloud.githubusercontent.com/assets/6042288/8956014/d33777f6-35bf-11e5-8620-d246ad6c05d5.png)

I am playing a song with PGMP; it's treated like a normal app and I can't play/pause from the notification screen:
![screenshot_2015-07-29-06-58-59](https://cloud.githubusercontent.com/assets/6042288/8956012/d330fe4e-35bf-11e5-8990-d597e6be608d.png)

MIUI is still displaying the last song I played with Shuttle+:
![screenshot_2015-07-29-06-59-04](https://cloud.githubusercontent.com/assets/6042288/8956013/d331d17a-35bf-11e5-9fe5-1849f85cded7.png)

**Comment by smithdtyler** [comment]
I will investigate the issue with it not showing up as a music application. The launcher behavior is expected.

**Comment by smithdtyler** [comment]
Hey, I updated the manifest so that PGMP *should* appear as a music application. I don't have a good way to test it, so please let me know if version 3.2.12 fixes this issue.

**Comment by tj28** [comment]
![screenshot_2015-08-23-14-08-55](https://cloud.githubusercontent.com/assets/6042288/9429530/3e3a453e-49a1-11e5-84d5-ba49e36024ab.png)
![screenshot_2015-08-23-14-09-25](https://cloud.githubusercontent.com/assets/6042288/9429532/4bba7972-49a1-11e5-9367-50ad69f20cad.png)
![screenshot_2015-08-23-14-09-41](https://cloud.githubusercontent.com/assets/6042288/9429534/56ba31dc-49a1-11e5-9845-ff83cd527378.png)

Still not resolved unfortunately. I really appreciate you working on this though!

**Comment by smithdtyler** [comment]
Did you download from FDroid? It usually takes about 24 hours for changes
to be reflected in the fdroid build.

**Comment by tj28** [comment]
Google play store. I'm not that familiar with Android but if you want to make a new branch I can try to compile and test commits

**Comment by smithdtyler** [comment]
My fix is in version 3.2.12. Google Play appears to have that version now,
but it might not have been live when you got the update?

If you did get the correct version and it's still not working, it would be
awesome if you could help test things out. The only problem is I'm not sure
what else I can do to fix this problem, since I already added the category
attribute to the application manifest...

Google play store. I'm not that familiar with Android but if you want to
make a new branch I can try to compile and test commits

—
Reply to this email directly or view it on GitHub
<https://github.com/smithdtyler/prettygoodmusicplayer/issues/92#issuecomment-133896491>
.

**Comment by tj28** [comment]
Are my (second pair of) three screenshots loading for you? The first one shows that I'm running 3.2.12, which I installed today, and the second and third ones show that the problem still exists. I just double checked and I didn't miss an update.

I'm happy to test further but I don't know what to mess with! PGMP is freaking perfect and I would really like to use my native music UI.

**Comment by smithdtyler** [comment]
Hmm... I'll have to look more closely at the applications which are appearing correctly for you. Thank goodness for open source software! 

I'll keep you posted, I hope I can fix this for you!

**Comment by smithdtyler** [comment]
For my own reference, the [VLC Android Source Code](https://code.openhub.net/file?fid=d8HHEehZIh5QIIBEzXzCeGHOWlo&cid=lwZ0wiHuiuY&s=&fp=395387&projSelected=true#L0)

**Comment by richq** [comment]
This patch makes PGMP appear on menus (tested with Amaze) however the NowPlaying screen just crashes out.

```
diff --git a/AndroidManifest.xml b/AndroidManifest.xml
index 6e74290..a0df6ac 100644
--- a/AndroidManifest.xml
+++ b/AndroidManifest.xml
@@ -50,6 +50,25 @@
             android:label="@string/title_activity_now_playing"
             android:exported="true"
         >
+            <intent-filter>
+                <action android:name="android.intent.action.VIEW" />
+                <category android:name="android.intent.category.DEFAULT" />
+                <data android:scheme="file"/>
+                <data android:mimeType="audio/*"/>
+                <data android:mimeType="application/ogg"/>
+                <data android:mimeType="application/x-ogg"/>
+                <data android:mimeType="application/x-flac"/>
+            </intent-filter>
+            <intent-filter>
+                <action android:name="android.intent.action.VIEW" />
+                <category android:name="android.intent.category.DEFAULT" />
+                <data android:scheme="content"/>
+                <data android:host="media"/>
+                <data android:mimeType="audio/*"/>
+                <data android:mimeType="application/ogg"/>
+                <data android:mimeType="application/x-ogg"/>
+                <data android:mimeType="application/x-flac"/>
+            </intent-filter>
         </activity>
         <!-- The service has android:exported="true" because that's needed for
         control from the notification. Not sure why it causes a warning... -->
```

The crash looks like this after adding that:

```
W/MusicPlaybackService( 1892): Caught exception while trying to pause 
W/MusicPlaybackService( 1892): java.lang.IllegalStateException
W/MusicPlaybackService( 1892):  at android.media.MediaPlayer._prepare(Native Method)
W/MusicPlaybackService( 1892):  at android.media.MediaPlayer.prepare(MediaPlayer.java:1135)
W/MusicPlaybackService( 1892):  at com.smithdtyler.prettygoodmusicplayer.MusicPlaybackService.pause(MusicPlaybackService.java:649)
W/MusicPlaybackService( 1892):  at com.smithdtyler.prettygoodmusicplayer.MusicPlaybackService.onStartCommand(MusicPlaybackService.java:277)
```

Probably NowPlaying wasn't expecting a file intent to appear. I'm not sure if "NowPlaying" is really the activity to use for this TBH. Also it appears a bit odd on the menu shown as "Open with Now Playing" probably the string title needs tweaking:

![open-with-now-playing](https://cloud.githubusercontent.com/assets/2865/10417869/0c5fe700-704b-11e5-8fa3-4fbcf92cad14.png)
